### Importar Arquivos e Bibliotecas

In [1]:
import pandas
import pathlib as pl
import win32com.client as win32

In [2]:

tabela_vendas = pandas.read_excel(r'Bases de dados\Vendas.xlsx')
tabela_lojas = pandas.read_csv(r'Bases de dados\Lojas.csv', encoding='latin1', sep=';')
tabela_emails = pandas.read_excel(r'Bases de dados\Emails.xlsx')

display(tabela_vendas)
display(tabela_lojas)
display(tabela_emails)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,1,Sapato Estampa,1,358,358
1,1,2019-01-01,1,Camiseta,2,180,360
2,1,2019-01-01,1,Sapato Xadrez,1,368,368
3,2,2019-01-02,3,Relógio,3,200,600
4,2,2019-01-02,3,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
100994,69996,2019-12-26,17,Short Listrado,2,102,204
100995,69996,2019-12-26,17,Mochila,4,270,1080
100996,69996,2019-12-26,17,Pulseira Estampa,1,87,87
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108
100998,69997,2019-12-26,11,Short Linho,2,133,266

    ID Loja                              Loja
0         1                Iguatemi Esplanada
1         2              Shopping Midway Mall
2         3                    Norte Shopping
3         4       Shopping Iguatemi Fortaleza
4         5          Shopping União de Osasco
5         6        Shopping Center Interlagos
6         7                    Rio Mar Recife
7         8                 Salvador Shopping
8         9        Rio Mar Shopping Fortaleza
9        10  Shopping Center Leste Aricanduva
10       11                 Ribeirão Shopping
11       12                  Shopping Morumbi
12       13         Parque Dom Pedro Shopping
13       14               Bourbon Shopping SP
14       15       Palladium Shopping Curitiba
15       16         Passei das Águas Shopping
16       17        Center Shopping Uberlândia
17       18                   Shopping Recife
18       19               Shopping Vila Velha
19       20                Shopping SP Market
20       21                 Shopping Eldorado
21       22               Shopping Ibirapuera
22       23      Novo Shopping Ribeirão Preto
23       24                 Iguatemi Campinas
24       25                    Shopping Barra

,Loja,Gerente,E-mail
0,Iguatemi Esplanada,Helena,medeirosjoaopim+helena@gmail.com
1,Shopping Midway Mall,Alice,medeirosjoaopim+alice@gmail.com
2,Norte Shopping,Laura,medeirosjoaopim+laura@gmail.com
3,Shopping Iguatemi Fortaleza,Manuela,medeirosjoaopim+manuela@gmail.com
4,Shopping União de Osasco,Valentina,medeirosjoaopim+valentina@gmail.com
5,Shopping Center Interlagos,Sophia,medeirosjoaopim+sophia@gmail.com
6,Rio Mar Recife,Isabella,medeirosjoaopim+isabella@gmail.com
7,Salvador Shopping,Heloisa,medeirosjoaopim+heloisa@gmail.com
8,Rio Mar Shopping Fortaleza,Luiza,medeirosjoaopim+luiza@gmail.com
9,Shopping Center Leste Aricanduva,Julia,medeirosjoaopim+julia@gmail.com
10,Ribeirão Shopping,Lorena,medeirosjoaopim+lorena@gmail.com
11,Shopping Morumbi,Livia,medeirosjoaopim+livia@gmail.com
12,Parque Dom Pedro Shopping,Maria Luiza,medeirosjoaopim+maria_luiza@gmail.com
13,Bourbon Shopping SP,Cecilia,medeirosjoaopim+cecilia@gmail.com
14,Palladium Shopping Curitiba,Eloa,medeirosjoaopim+eloa@gmail.com
15,Passei das Águas Shopping,Miguel,medeirosjoaopim+miguel@gmail.com
16,Center Shopping Uberlândia,Arthur,medeirosjoaopim+arthur@gmail.com
17,Shopping Recife,Heitor,medeirosjoaopim+heitor@gmail.com
18,Shopping Vila Velha,Bernardo,medeirosjoaopim+bernardo@gmail.com
19,Shopping SP Market,Davi,medeirosjoaopim+davi@gmail.com
20,Shopping Eldorado,Theo,medeirosjoaopim+theo@gmail.com
21,Shopping Ibirapuera,Lorenzo,medeirosjoaopim+lorenzo@gmail.com
22,Novo Shopping Ribeirão Preto,Gabriel,medeirosjoaopim+gabriel@gmail.com
23,Iguatemi Campinas,Pedro,medeirosjoaopim+pedro@gmail.com
24,Shopping Barra,Benjamin,medeirosjoaopim+benjamin@gmail.com
25,Diretoria,Diretoria,medeirosjoaopim+diretoria@gmail.com

### Definir Criar uma Tabela para cada Loja e Definir o dia do Indicador

In [ ]:
tabela_vendas = tabela_vendas.merge(tabela_lojas, on='ID Loja')

In [ ]:
dicionario_lojas = {}
for loja in tabela_lojas['Loja']:
    dicionario_lojas[loja] = tabela_vendas.loc[tabela_vendas['Loja'] == loja, :]

display(dicionario_lojas['Norte Shopping'])
display(dicionario_lojas['Ribeirão Shopping'])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
3,2,2019-01-02,3,Relógio,3,200,600,Norte Shopping
4,2,2019-01-02,3,Chinelo Liso,1,71,71,Norte Shopping
8,7,2019-01-02,3,Camisa Gola V Listrado,1,116,116,Norte Shopping
9,7,2019-01-02,3,Camisa Liso,1,105,105,Norte Shopping
100,73,2019-01-02,3,Cueca Xadrez,5,60,300,Norte Shopping
...,...,...,...,...,...,...,...,...
100830,69888,2019-12-25,3,Tênis Linho,1,294,294,Norte Shopping
100878,69916,2019-12-25,3,Terno,2,700,1400,Norte Shopping
100945,69962,2019-12-25,3,Meia Linho,2,78,156,Norte Shopping
100968,69976,2019-12-26,3,Tênis Xadrez,1,259,259,Norte Shopping
100969,69976,2019-12-26,3,Casaco,4,250,1000,Norte Shopping

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
81,62,2019-01-02,11,Camisa Gola V Estampa,1,118,118,Ribeirão Shopping
82,62,2019-01-02,11,Chinelo Estampa,2,74,148,Ribeirão Shopping
109,84,2019-01-02,11,Pulseira Xadrez,5,87,435,Ribeirão Shopping
110,84,2019-01-02,11,Sapato Liso,3,368,1104,Ribeirão Shopping
111,84,2019-01-02,11,Calça,1,170,170,Ribeirão Shopping
...,...,...,...,...,...,...,...,...
100953,69967,2019-12-25,11,Short,1,90,90,Ribeirão Shopping
100954,69967,2019-12-25,11,Bermuda Linho,1,195,195,Ribeirão Shopping
100983,69984,2019-12-26,11,Cueca Liso,4,69,276,Ribeirão Shopping
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108,Ribeirão Shopping
100998,69997,2019-12-26,11,Short Linho,2,133,266,Ribeirão Shopping

In [ ]:
dia_indicador = tabela_vendas['Data'].max()
print(dia_indicador)

2019-12-26 00:00:00

### Salvar a planilha na pasta de backup

In [ ]:
caminho = pl.Path(r'Backup Arquivos Lojas')

arquivos_pasta = caminho.iterdir()

lista_arquivos = [arquivo.name for arquivo in arquivos_pasta]

for loja in dicionario_lojas:
    if loja not in lista_arquivos:
        nova_pasta = caminho / loja
        nova_pasta.mkdir()
    
    #salvar dentro da pasta da loja de backup
    nome_arquivo = f'{loja}_{dia_indicador.day}_{dia_indicador.month}_{dia_indicador.year}.xlsx'
    local_arquivo = caminho / loja / nome_arquivo
    dicionario_lojas[loja].to_excel(local_arquivo)

### Calcular o indicador para 1 loja e enviar Email

In [6]:
meta_faturamento_dia = 1000
meta_faturamento_ano = 1650000
meta_qtdeprodutos_dia = 4
meta_qtdeprodutos_ano = 120
meta_ticketmedio_dia = 500
meta_ticketmedio_ano = 500

In [ ]:
for loja in dicionario_lojas:

    vendas_loja = dicionario_lojas[loja]
    vendas_loja_dia = vendas_loja.loc[vendas_loja['Data']==dia_indicador, :]

    #faturamento
    faturamento_ano = vendas_loja['Valor Final'].sum()
    #print(faturamento_ano)
    faturamento_dia = vendas_loja_dia['Valor Final'].sum()
    #print(faturamento_dia)

    #diversidade de produtos
    qtde_produtos_ano = len(vendas_loja['Produto'].unique())
    #print(qtde_produtos_ano)
    qtde_produtos_dia = len(vendas_loja_dia['Produto'].unique())
    #print(qtde_produtos_dia)


    #ticket medio
    valor_venda = vendas_loja.groupby('Código Venda').sum(numeric_only=True)
    ticket_medio_ano = valor_venda['Valor Final'].mean()
    #print(ticket_medio_ano)
    #ticket_medio_dia
    valor_venda_dia = vendas_loja_dia.groupby('Código Venda').sum(numeric_only=True)
    ticket_medio_dia = valor_venda_dia['Valor Final'].mean()
    #print(ticket_medio_dia)
    
    
    #enviar o e-mail
    outlook = win32.Dispatch('outlook.application')

    nome = tabela_emails.loc[tabela_emails['Loja']==loja, 'Gerente'].values[0]
    mail = outlook.CreateItem(0)
    mail.To = tabela_emails.loc[tabela_emails['Loja']==loja, 'E-mail'].values[0]
    mail.Subject = f'OnePage Dia {dia_indicador.day}/{dia_indicador.month} - Loja {loja}'
    #mail.Body = 'Texto do E-mail'
    
    if faturamento_dia >= meta_faturamento_dia:
        cor_fat_dia = 'green'
    else:
        cor_fat_dia = 'red'
    if faturamento_ano >= meta_faturamento_ano:
        cor_fat_ano = 'green'
    else:
        cor_fat_ano = 'red'
    if qtde_produtos_dia >= meta_qtdeprodutos_dia:
        cor_qtde_dia = 'green'
    else:
        cor_qtde_dia = 'red'
    if qtde_produtos_ano >= meta_qtdeprodutos_ano:
        cor_qtde_ano = 'green'
    else:
        cor_qtde_ano = 'red'
    if ticket_medio_dia >= meta_ticketmedio_dia:
        cor_ticket_dia = 'green'
    else:
        cor_ticket_dia = 'red'
    if ticket_medio_ano >= meta_ticketmedio_ano:
        cor_ticket_ano = 'green'
    else:
        cor_ticket_ano = 'red'

    mail.HTMLBody = f'''
    <p>Bom dia, {nome}</p>

    <p>O resultado de ontem <strong>({dia_indicador.day}/{dia_indicador.month})</strong> da <strong>Loja {loja}</strong> foi:</p>

    <table>
      <tr>
        <th>Indicador</th>
        <th>Valor Dia</th>
        <th>Meta Dia</th>
        <th>Cenário Dia</th>
      </tr>
      <tr>
        <td>Faturamento</td>
        <td style="text-align: center">R${faturamento_dia:.2f}</td>
        <td style="text-align: center">R${meta_faturamento_dia:.2f}</td>
        <td style="text-align: center"><font color="{cor_fat_dia}">◙</font></td>
      </tr>
      <tr>
        <td>Diversidade de Produtos</td>
        <td style="text-align: center">{qtde_produtos_dia}</td>
        <td style="text-align: center">{meta_qtdeprodutos_dia}</td>
        <td style="text-align: center"><font color="{cor_qtde_dia}">◙</font></td>
      </tr>
      <tr>
        <td>Ticket Médio</td>
        <td style="text-align: center">R${ticket_medio_dia:.2f}</td>
        <td style="text-align: center">R${meta_ticketmedio_dia:.2f}</td>
        <td style="text-align: center"><font color="{cor_ticket_dia}">◙</font></td>
      </tr>
    </table>
    <br>
    <table>
      <tr>
        <th>Indicador</th>
        <th>Valor Ano</th>
        <th>Meta Ano</th>
        <th>Cenário Ano</th>
      </tr>
      <tr>
        <td>Faturamento</td>
        <td style="text-align: center">R${faturamento_ano:.2f}</td>
        <td style="text-align: center">R${meta_faturamento_ano:.2f}</td>
        <td style="text-align: center"><font color="{cor_fat_ano}">◙</font></td>
      </tr>
      <tr>
        <td>Diversidade de Produtos</td>
        <td style="text-align: center">{qtde_produtos_ano}</td>
        <td style="text-align: center">{meta_qtdeprodutos_ano}</td>
        <td style="text-align: center"><font color="{cor_qtde_ano}">◙</font></td>
      </tr>
      <tr>
        <td>Ticket Médio</td>
        <td style="text-align: center">R${ticket_medio_ano:.2f}</td>
        <td style="text-align: center">R${meta_ticketmedio_ano:.2f}</td>
        <td style="text-align: center"><font color="{cor_ticket_ano}">◙</font></td>
      </tr>
    </table>

    <p>Segue em anexo a planilha com todos os dados para mais detalhes.</p>

    <p>Qualquer dúvida estou à disposição.</p>
    <p>Att., Joao Medeiros</p>
    '''

    # Anexos (pode colocar quantos quiser):
    attachment  = pl.Path.cwd() / caminho / loja / f'{loja}_{dia_indicador.day}_{dia_indicador.month}_{dia_indicador.year}.xlsx'
    mail.Attachments.Add(str(attachment))

    mail.Send()
    print('E-mail da Loja {} enviado'.format(loja))

E-mail da Loja Iguatemi Esplanada enviado
E-mail da Loja Shopping Midway Mall enviado
E-mail da Loja Norte Shopping enviado
E-mail da Loja Shopping Iguatemi Fortaleza enviado
E-mail da Loja Shopping União de Osasco enviado
E-mail da Loja Shopping Center Interlagos enviado
E-mail da Loja Rio Mar Recife enviado
E-mail da Loja Salvador Shopping enviado
E-mail da Loja Rio Mar Shopping Fortaleza enviado
E-mail da Loja Shopping Center Leste Aricanduva enviado
E-mail da Loja Ribeirão Shopping enviado
E-mail da Loja Shopping Morumbi enviado
E-mail da Loja Parque Dom Pedro Shopping enviado
E-mail da Loja Bourbon Shopping SP enviado
E-mail da Loja Palladium Shopping Curitiba enviado
E-mail da Loja Passei das Águas Shopping enviado
E-mail da Loja Center Shopping Uberlândia enviado
E-mail da Loja Shopping Recife enviado
E-mail da Loja Shopping Vila Velha enviado
E-mail da Loja Shopping SP Market enviado
E-mail da Loja Shopping Eldorado enviado
E-mail da Loja Shopping Ibirapuera enviado
E-mail da Loja Novo Shopping Ribeirão Preto enviado
E-mail da Loja Iguatemi Campinas enviado
E-mail da Loja Shopping Barra enviado

### Enviar por e-mail para o gerente

In [17]:
faturamento_lojas_ano = tabela_vendas.groupby('Loja')[['Loja', 'Valor Final']].sum(numeric_only=True)
faturamento_lojas_ano = faturamento_lojas_ano.sort_values(by='Valor Final', ascending=False)

nome_arquivo = '{}_{}_Ranking Anual.xlsx'.format(dia_indicador.month, dia_indicador.day)
faturamento_lojas_ano.to_excel(r'Backup Arquivos Lojas\{}'.format(nome_arquivo))

faturamento_lojas_dia = tabela_vendas.loc[tabela_vendas['Data']==dia_indicador, :].groupby('Loja')[['Loja', 'Valor Final']].sum(numeric_only=True)
faturamento_lojas_dia = faturamento_lojas_dia.sort_values(by='Valor Final', ascending=False)

nome_arquivo = '{}_{}_Ranking Dia.xlsx'.format(dia_indicador.month, dia_indicador.day)
faturamento_lojas_dia.to_excel(r'Backup Arquivos Lojas\{}'.format(nome_arquivo))

display(faturamento_lojas_ano)
display(faturamento_lojas_dia)

                                  Valor Final
Loja
Iguatemi Campinas                     1762419
Shopping Vila Velha                   1731167
Bourbon Shopping SP                   1726110
Rio Mar Recife                        1722766
Shopping SP Market                    1721763
Palladium Shopping Curitiba           1721120
Norte Shopping                        1711968
Ribeirão Shopping                     1707122
Iguatemi Esplanada                    1699681
Rio Mar Shopping Fortaleza            1698430
Shopping Center Leste Aricanduva      1682870
Novo Shopping Ribeirão Preto          1678225
Shopping Iguatemi Fortaleza           1674824
Center Shopping Uberlândia            1668921
Shopping União de Osasco              1663770
Shopping Barra                        1653103
Passei das Águas Shopping             1649014
Shopping Eldorado                     1648111
Salvador Shopping                     1646739
Shopping Center Interlagos            1640486
Shopping Ibirapuera                   1635060
Parque Dom Pedro Shopping             1631630
Shopping Recife                       1624879
Shopping Midway Mall                  1590441
Shopping Morumbi                      1586444

                                  Valor Final
Loja
Salvador Shopping                        3950
Novo Shopping Ribeirão Preto             3400
Center Shopping Uberlândia               2651
Shopping Eldorado                        2391
Shopping Center Interlagos               1582
Shopping Recife                          1366
Norte Shopping                           1259
Shopping União de Osasco                 1207
Shopping Vila Velha                       937
Bourbon Shopping SP                       676
Ribeirão Shopping                         650
Shopping Center Leste Aricanduva          485
Palladium Shopping Curitiba               381
Rio Mar Shopping Fortaleza                368
Shopping Midway Mall                      170
Shopping Ibirapuera                       118

In [ ]:
#Enviar email

outlook = win32.Dispatch('outlook.application')

mail = outlook.CreateItem(0)
mail.To = tabela_emails.loc[tabela_emails['Loja']=='Diretoria', 'E-mail'].values[0]
mail.Subject = f'Ranking Dia {dia_indicador.day}/{dia_indicador.month}'
mail.Body = f'''
Prezados, bom dia

Melhor loja do Dia em Faturamento: Loja {faturamento_lojas_dia.index[0]} com Faturamento R${faturamento_lojas_dia.iloc[0, 0]:.2f}
Pior loja do Dia em Faturamento: Loja {faturamento_lojas_dia.index[-1]} com Faturamento R${faturamento_lojas_dia.iloc[-1, 0]:.2f}

Melhor loja do Ano em Faturamento: Loja {faturamento_lojas_ano.index[0]} com Faturamento R${faturamento_lojas_ano.iloc[0, 0]:.2f}
Pior loja do Ano em Faturamento: Loja {faturamento_lojas_ano.index[-1]} com Faturamento R${faturamento_lojas_ano.iloc[-1, 0]:.2f}

Segue em anexo os rankings do ano e do dia de todas as lojas.

Qualquer dúvida estou à disposição.

Att.,
Joao Medeiros
'''

# Anexos (pode colocar quantos quiser):
attachment  = pl.Path.cwd() / caminho / f'{dia_indicador.month}_{dia_indicador.day}_Ranking Anual.xlsx'
mail.Attachments.Add(str(attachment))
attachment  = pl.Path.cwd() / caminho / f'{dia_indicador.month}_{dia_indicador.day}_Ranking Dia.xlsx'
mail.Attachments.Add(str(attachment))


mail.Send()
print('E-mail da Diretoria enviado')

E-mail da Diretoria enviado